path: .
train: images/train
val: images/val
test: images/test
names:
  0: battery
  1: button
  2: buzzer
  3: capacitor
  4: clock
  5: connector
  6: diode
  7: display
  8: ferrite_bead
  9: fuse
  10: heatsink
  11: ic_chip
  12: inductor
  13: jumper
  14: led
  15: pad
  16: pin
  17: potentiometer
  18: resistor
  19: switch
  20: test_point
  21: transformer
  22: transistor
  23: unknown_component
  24: vortex_mixer
  25: centrifuge_tube
  26: tube_cap
  27: tube_rack
  28: arduino_board
  29: breadboard
  30: sensor_module
  31: electronic_module
  32: motor
  33: relay_module
  34: ic_socket
  35: keypad
  36: function_generator
  37: multimeter
  38: oscilloscope
  39: power_supply
  40: digital_trainer
  41: lab_breadboard_trainer
  42: power_strip
  43: component_box
  44: raspberry_pi
  45: bnc_cable
  46: probe
  47: wire
  48: transformer_device
  49: variable_transformer
  50: ammeter
  51: voltmeter
  52: stopwatch
  53: resistance_box
  54: capacitor_box
  55: bulb_socket
  56: bulb
  57: electronic_balance
  58: electroscope
  59: experiment_apparatus
  60: timer
  61: galvanometer
  62: lamp
  63: calorimeter
  64: magnet
  65: amplifier
  66: polarizer
  67: rheostat
  68: screwdriver
  69: solenoid
  70: tesla_coil
  71: teslameter
  72: electronics_kit
  73: vacuum_pump
